#!/usr/bin/env bash
# ./meta — thin launcher for the ai-meta binary. GENERATED by `meta init/upgrade`.
# Do not edit; the pinned version lives in .meta/version. See
# https://github.com/tizz98/ai-meta
set -euo pipefail

root="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ver="$(cat "$root/.meta/version" 2>/dev/null || true)"
if [ -z "$ver" ]; then
  echo "meta: missing .meta/version (run 'meta init')" >&2
  exit 1
fi

case "$(uname -s)-$(uname -m)" in
  Linux-x86_64)   tgt=x86_64-unknown-linux-musl ;;
  Linux-aarch64)  tgt=aarch64-unknown-linux-musl ;;
  Darwin-arm64)   tgt=aarch64-apple-darwin ;;
  Darwin-x86_64)  tgt=x86_64-apple-darwin ;;
  *) echo "meta: unsupported platform $(uname -s)-$(uname -m)" >&2; exit 1 ;;
esac

cache="${AI_META_CACHE:-$HOME/.cache/ai-meta}/$ver"
bin="$cache/ai-meta-$tgt"

if [ ! -x "$bin" ]; then
  mkdir -p "$cache"
  base="https://github.com/tizz98/ai-meta/releases/download/v$ver"
  if ! curl -fsSL "$base/ai-meta-$tgt" -o "$bin.tmp"; then
    echo "meta: failed to download ai-meta v$ver for $tgt from $base" >&2
    exit 1
  fi
  if curl -fsSL "$base/ai-meta-$tgt.sha256" -o "$bin.sha256" 2>/dev/null; then
    # The checksum file may be either "<sum>" or "<sum>  <name>"; normalize.
    sum="$(awk '{print $1}' "$bin.sha256")"
    if command -v sha256sum >/dev/null 2>&1; then
      have="$(sha256sum "$bin.tmp" | awk '{print $1}')"
    else
      have="$(shasum -a 256 "$bin.tmp" | awk '{print $1}')"
    fi
    if [ "$sum" != "$have" ]; then
      echo "meta: checksum mismatch for ai-meta v$ver ($tgt)" >&2
      rm -f "$bin.tmp"
      exit 1
    fi
  fi
  chmod +x "$bin.tmp"
  mv "$bin.tmp" "$bin"
fi

exec "$bin" "$@"
