#Requires -Version 5.1
# .meta/shim.ps1 — PowerShell launcher for the ai-meta binary. GENERATED by
# `meta init/upgrade`. Do not edit; the pinned version lives in .meta/version.
# Reached via the repo-root meta.cmd dispatcher. See
# https://github.com/tizz98/ai-meta
$ErrorActionPreference = 'Stop'

# The pinned version sits next to this script (.meta/version).
$verFile = Join-Path $PSScriptRoot 'version'
$ver = ''
if (Test-Path -LiteralPath $verFile) {
  $raw = Get-Content -Raw -LiteralPath $verFile
  if ($raw) { $ver = $raw.Trim() }
}
if (-not $ver) {
  [Console]::Error.WriteLine("meta: missing .meta/version (run 'meta init')")
  exit 1
}

# Map the host arch to a release target. Only x86_64 Windows is published today.
switch ($env:PROCESSOR_ARCHITECTURE) {
  'AMD64' { $tgt = 'x86_64-pc-windows-msvc'; $ext = '.exe' }
  'x86'   { $tgt = 'x86_64-pc-windows-msvc'; $ext = '.exe' }
  default {
    [Console]::Error.WriteLine("meta: unsupported Windows arch $($env:PROCESSOR_ARCHITECTURE) (no published build)")
    exit 1
  }
}

# Share the download cache with the bash shim ($HOME/.cache/ai-meta/<ver>).
$cacheRoot = if ($env:AI_META_CACHE) { $env:AI_META_CACHE } else { Join-Path $HOME '.cache\ai-meta' }
$cache = Join-Path $cacheRoot $ver
$asset = "ai-meta-$tgt$ext"
$bin = Join-Path $cache $asset

if (-not (Test-Path -LiteralPath $bin)) {
  New-Item -ItemType Directory -Force -Path $cache | Out-Null
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  $ProgressPreference = 'SilentlyContinue'
  $base = "https://github.com/tizz98/ai-meta/releases/download/v$ver"
  $tmp = "$bin.tmp"
  try {
    Invoke-WebRequest -UseBasicParsing -Uri "$base/$asset" -OutFile $tmp
  } catch {
    [Console]::Error.WriteLine("meta: failed to download ai-meta v$ver for $tgt from $base")
    exit 1
  }
  # Verify the checksum when the release publishes one (it always should).
  $sumFile = "$bin.sha256"
  $haveSum = $false
  try {
    Invoke-WebRequest -UseBasicParsing -Uri "$base/$asset.sha256" -OutFile $sumFile
    $haveSum = $true
  } catch { }
  if ($haveSum) {
    $want = (((Get-Content -Raw -LiteralPath $sumFile).Trim()) -split '\s+')[0].ToLower()
    $have = (Get-FileHash -Algorithm SHA256 -LiteralPath $tmp).Hash.ToLower()
    if ($want -and ($want -ne $have)) {
      Remove-Item -Force -LiteralPath $tmp
      [Console]::Error.WriteLine("meta: checksum mismatch for ai-meta v$ver ($tgt)")
      exit 1
    }
  }
  Move-Item -Force -LiteralPath $tmp -Destination $bin
}

# Match `exec "$bin" "$@"` — inherit cwd; do not let a nonzero native exit throw.
$ErrorActionPreference = 'Continue'
& $bin @args
exit $LASTEXITCODE
