@echo off
setlocal
rem meta.cmd - Windows dispatcher for the ai-meta launcher. GENERATED by
rem `meta init/upgrade`. Routes PowerShell (./meta) and cmd.exe (.\meta) through
rem PowerShell with -ExecutionPolicy Bypass into .meta\shim.ps1, so `./meta` works
rem under any execution policy. Do not edit. https://github.com/tizz98/ai-meta
set "PS=powershell"
where /q pwsh && set "PS=pwsh"
"%PS%" -NoProfile -ExecutionPolicy Bypass -File "%~dp0.meta\shim.ps1" %*
exit /b %errorlevel%
